# Einfeldt 1-2-3 strong rarefaction
[problem]
problem = "sod"
t_end = 0.15
nlim = -1
geometry = "planar"
restart = false
xl = 0.0
xr = 1.0
cfl = 0.5
nx = 2048

[problem.params]
vL = -2.0
vR = +2.0
rhoL = 1.0
rhoR = 1.0
pL = 0.4
pR = 0.4
x_d = 0.5

[physics]
radiation = false
gravity = false
composition = false
ionization = false

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"

[output]
ncycle_out = 100
#dt_hdf5 = 1.0e-2
dt_init_frac = 1.25

[output.history]
fn = "einfeldt.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 3
porder = 3

[fluid.limiter]
do_limiter = true
type = "minmod"
m_tvb = 5.0
b_tvd = 1.0
tci_opt = true
tci_val = 1.0e-1
characteristic = false
gamma_i = 0.998

[time]
integrator = "EX_SSPRK22"

[eos]
type = "ideal"
gamma = 1.4 # default: 1.4
