# Einfeldt 1-2-3 strong rarefaction
[problem]
problem = "sod"
t_end = 0.15
geometry = "planar"
restart = false
do_rad = false
xl = 0.0
xr = 1.0
cfl = 0.7

[problem.params]
vL = -2.0
vR = +2.0
rhoL = 1.0
rhoR = 1.0
pL = 1.2
pR = 1.2
x_d = 0.5

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"

[output]
nlim = -1
ncycle_out = 100
#dt_hdf5 = 1.0e-2
dt_init_frac = 1.25

[fluid]
basis = "legendre"
nnodes = 2
porder = 2
nx = 256
ng = 1

[time]
integrator = "EX_SSPRK3"

[eos]
type = "ideal"
ideal_gamma = 1.4 # default: 1.4

# slope limiter is bad for this problem?
[limiters]
do_limiter = true
type = "minmod"
m_tvb = 100.0
b_tvd = 1.0
tci_opt = true
tci_val = 1.0e-1
characteristic = false
gamma_i = 0.998
weno_r = 1
#gamma_r = 0.005
#gamma_l = 0.005
#b_tvd = 2.0 #minmod
#m_tvb = 1.0 #minmod
