[problem]
problem = "ejecta_csm"
t_end = 0.05
nlim = -1
geometry = "spherical"
restart = false
xl = 0.0
xr = 1.0
cfl = 0.5
nx = 256

[physics]
radiation = false
gravity = false
composition = false
ionization = false

[problem.params]
rstar = 0.01
vmax = 1.8257418583505537 # sqrt(10/3)

#[bc]
[bc.fluid]
bc_i = "reflecting"
bc_o = "outflow"

[output]
ncycle_out = 100
#dt_hdf5 = 2.5e-2
dt_init_frac = 1.01

[output.history]
fn = "ejecta_csm.hst"
dt = 0.001

[fluid]
basis = "legendre"
nnodes = 1
porder = 1

[fluid.limiter]
do_limiter = true
type = "minmod"
m_tvb = 10.0
b_tvd = 1.0
tci_opt = true
tci_val = 0.075
characteristic = false

[time]
integrator = "EX_SSPRK33"

[eos]
type = "ideal"
gamma = 1.6666666667 # default: 1.4
