[problem]
problem = "hydrostatic_balance"
t_end = 50.0
nlim = -1
geometry = "spherical"
restart = false
xl = 0.0
xr = 5.0e10
cfl = 0.05
nx = 512

[problem.params]
rho_c = 1.0e2

[physics]
radiation = false
gravity = true
composition = false
ionization = false

[bc]
[bc.fluid]
bc_i = "reflecting"
bc_o = "outflow"

[output]
ncycle_out = 100
dt_hdf5 = 0.1
dt_init_frac = 1.001

[output.history]
fn = "gas_collapse.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 1
porder = 1

[fluid.limiter]
do_limiter = true
type = "minmod"
b_tvd = 0.0
m_tvb = 0.0
tci_opt = true
tci_val = 0.25
characteristic = false
gamma_i = 0.9
#gamma_r = 0.005
#gamma_l = 0.005
weno_r = 2.0

[gravity]
model = "spherical"
gval = 1.0e3

[time]
integrator = "EX_SSPRK33"

[eos]
type = "polytropic"
#k = 7.125e14
k = 1.0e13
n = 3.0
