[problem]
problem = "sod"
t_end = 6.0
nlim = -1
geometry = "planar"
xl = 0.0
xr = 10.0
cfl = 0.1
nx = 2048

[problem.params]
vL = 0.0
vR = 0.0
rhoL = 1.0
rhoR = 1.0e-3
pL = 0.066666667
pR = 0.666666667e-10
x_d = 3.0

[physics]
radiation = false
gravity = false

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"

[output]
ncycle_out = 100
dt_hdf5 = 1.0e-2
dt_init_frac = 1.1

[output.history]
fn = "leblanc.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 1
porder = 1


[fluid.limiter]
do_limiter = true
type = "minmod"
m_tvb = 0.0
b_tvd = 1.0
tci_opt = false
tci_val = 1.0e-5
characteristic = true
gamma_i = 0.1
#gamma_r = 0.005
#gamma_l = 0.005
#b_tvd = 2.0 #minmod
#m_tvb = 1.0 #minmod

[time]
integrator = "EX_SSPRK22"

[eos]
type = "ideal"
gamma = 1.66666666667 # default: 1.4
