[problem]
problem = "marshak"
t_end = 5.781e-14
geometry = "planar"
restart = false
do_rad = true
xl = 0.0
xr = 3.466205e-3
cfl = 0.5

[problem.params]
v0 = 0.0
rho0 = 10.0
T0 = 1.0e4
epsilon = 1.0

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"
[bc.rad]
bc_i = "dirichlet"
bc_o = "outflow"
dirichlet_values_i = [1.111045879098685e11, 0.0]

[output]
nlim = -1
ncycle_out = 250
#dt_hdf5 = 1.0e-12 # default: 100 outputs
dt_init_frac = 1.00001

[fluid]
basis = "legendre"
nnodes = 1
porder = 1
nx = 128
ng = 1

[time]
torder = 1
nstages = 1

[eos]
type = "ideal"
ideal_gamma = 1.66666666666667 # default: 1.4

[opacity]
type = "constant"
kP = 577.0 # cm^2 / g
kR = 577.0 # cm^2 / g

[limiters]
type = "minmod"
m_tvb = 0.0
b_tvd = 1.0
tci_opt = false
tci_val = 0.1
characteristic = false
