[problem]
problem = "marshak"
t_end = 5.781e-14
nlim = -1
geometry = "planar"
restart = false
xl = 0.0
xr = 3.466205e-3
cfl = 0.3
nx = 256
grid_type = "uniform"

[problem.params]
v0 = 0.0
rho0 = 10.0
T0 = 1.0e4
epsilon = 1.0

[physics]
radiation = true
gravity = false
composition = false
ionization = false
heating = false

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"
[bc.radiation]
bc_i = "marshak"
bc_o = "outflow"
dirichlet_values_i = [1.1113063385e12, 0.0]

[output]
ncycle_out = 100
#dt_hdf5 = 1.0e-12 # default: 100 outputs
dt_init_frac = 1.0005

[output.history]
fn = "marshak.hst"
dt = 1.0e-16

[fluid]
basis = "legendre"
nnodes = 1
porder = 1

[fluid.limiter]
do_limiter = true
type = "minmod"
m_tvb = 0.0
b_tvd = 1.0
tci_opt = false
tci_val = 0.1
characteristic = false

[radiation]
basis = "legendre"
nnodes = 1
porder = 1

[radiation.limiter]
do_limiter = true
type = "minmod"
m_tvb = 1000.0
b_tvd = 2.0
tci_opt = true
tci_val = 0.1
characteristic = false

[time]
#integrator = "IMEX_ARK32_ESDIRK"
#integrator = "IMEX_PDARS_ESDIRK"
integrator = "IMEX_SSPRK11"

[eos]
type = "marshak"
gamma = 1.66666666666667 # default: 1.4

[opacity]
type = "constant"
kP = 577.0 # cm^2 / g
kR = 577.0 # cm^2 / g
