[problem]
problem = "moving_contact"
t_end = 1.0
geometry = "planar"
restart = false
do_rad = false
xl = 0.0
xr = 1.0
bc = "periodic"
cfl = 0.35

[problem.params]
v0 = 0.1
rhoL = 1.4
rhoR = 1.0

[output]
nlim = -1
ncycle_out = 100
dt_hdf5 = 0.1

[fluid]
basis = "legendre"
nnodes = 1
pprder = 1
nx = 128
ng = 1

[time]
torder = 1
nstages = 1

[limiters]
tci_opt = false
tci_val = 0.1
characteristic = true
