[problem]
problem = "moving_contact"
t_end = 5.0
geometry = "planar"
restart = false
do_rad = true
xl = 0.0
xr = 1.0
bc = "homogenous"
cfl = 0.35

[fluid]
basis = "legendre"
nnodes = 1
pprder = 1
nx = 128
ng = 1

[time]
torder = 1
nstages = 1

[limiters]
tci_opt = false
tci_val = 0.1
characteristic = true
