[problem]
problem = "ni_decay"
t_end = 524880.0 # one half-life of 56Ni
nlim = -1
geometry = "spherical"
restart = false
xl = 0.0
xr = 3.622e9
cfl = 0.8
nx = 16
grid_type = "uniform"

[problem.params]
temperature = 1000.0
rho = 1000.0

[physics]
radiation = false
gravity = false
composition = true
ionization = false
heating = true

[heating.nickel]
enabled = true
model = "full_trapping"

[bc]
[bc.fluid]
bc_i = "reflecting"
bc_o = "outflow"

[output]
ncycle_out = 250
#dt_hdf5 = 1.0e-12 # default: 100 outputs
dt_init_frac = 1.01

[output.history]
fn = "ni_decay.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 2
porder = 2

[fluid.limiter]
do_limiter = true
tci_opt = false
tci_val = 0.1
characteristic = false

[time]
integrator = "EX_SSPRK22"

[eos]
type = "ideal"
gamma = 1.4 # default: 1.4
