[problem]
problem = "noh"
t_end = 0.5
geometry = "planar"
restart = false
xl = 0.0
xr = 1.0
cfl = 0.1
nx = 128

[problem.params]
v0 = -1.0
rho0 = 1.0
p0 = 0.000001

[physics]
radiation = false
gravity = false

[bc]
[bc.fluid]
bc_i = "reflecting"
bc_o = "outflow"

[output]
nlim = -1
ncycle_out = 100
dt_hdf5 = 0.1
dt_init_frac = 1.01

[output.history]
fn = "noh.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 2
porder = 2

[fluid.limiter]
do_limiter = true
type = "minmod"
b_tvd = 1.0
m_tvb = 0.0
tci_opt = false
tci_val = 0.1
characteristic = true
gamma_i = 0.8

[time]
integrator = "EX_SSPRK22"

[eos]
type = "ideal"
gamma = 1.6666666667
