[problem]
problem = "rad_shock_steady"
t_end = 1.0e-11
geometry = "planar"
restart = false
xl = -0.03
xr = 0.03
cfl = 0.8
nx = 128

# Mach 2 Case:
# - Left side (pre-shock):
#   - Density: 1.0 g/cm^3
#   - Temperature: 1.16045181e6 K (100eV)
# - Right side (post-shock):
#   - Density: 2.286 g/cm^3
#   - Temperature: 2.4109e6 K (207.756 eV)
# 
# Mach 5 Case:
# - Left side (pre-shock):
#   - Density: 1.0 g/cm^3
#   - Temperature: 1.16045181e6 K (100 eV)
# - Right side (post-shock):
#   - Density: 3.598 g/cm^3
#   - Temperature: 9.9302e6 K (855.720 eV)
[problem.params]
v0 = 0.0
rhoL = 1.0
rhoR = 2.286 
T_L = 1.16045181e6
T_R = 2.4109e6

[physics]
radiation = true
gravity = false

# TODO(astrobarker) fix
[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"
[bc.radiation]
bc_i = "outflow"
bc_o = "outflow"

[output]
nlim = -1
ncycle_out = 100
#dt_hdf5 = 1.0e-10 # default: 100 outputs
dt_init_frac = 1.0001

[output.history]
fn = "rad_shock_steady.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 1
porder = 1

[fluid.limiter]
type = "minmod"
tci_opt = false
tci_val = 0.1
characteristic = false

[radiation]
basis = "legendre"
nnodes = 1
porder = 1

[radiation.limiter]
tci_opt = false
tci_val = 0.1
characteristic = false

[time]
integrator = "IMEX_SSPRK22_DIRK"

[eos]
type = "ideal"
ideal_gamma = 1.66666666666667 # default: 1.4

[opacity]
type = "powerlaw_rho"
kP = 422.99 # 1 / cm
kR = 788.03 # 1 / cm
exp = -1.0
