[problem]
problem = "rad_shock"
t_end = 0.2e-9
nlim = -1
geometry = "planar"
restart = false
xl = 0.0
xr = 0.01575
x_d = 0.0132
cfl = 0.95
nx = 256
grid_type = "uniform"

# Mach 3 Case:
# - Left side (pre-shock):
#   - Density: 5.69 g/cm^3
#   - Velocity: 5.19e7 cm / s
#   - Temperature: 2.18e6 K
# - Right side (post-shock):
#   - Density: 17.1 g/cm^3
#   - Velocity: 1.73e7 cm/s
#   - Temperature: 7.98e6 K
[problem.params]
vL = 5.19e7
vR = 1.73e7
#vL = 0.0
#vR = 0.0
rhoL = 5.69
rhoR = 17.1 
T_L = 2.18e6
T_R = 7.98e6

[physics]
radiation = true
gravity = false
composition = false
ionization = false
heating = false

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"
dirichlet_values_i = [1.757469e-1, 5.19e7, 1.6165769496e15]
dirichlet_values_o = [5.847953e-2, 1.73e7, 1.1371588340e15]
[bc.radiation]
bc_i = "outflow"
bc_o = "outflow"
dirichlet_values_i = [1.7087439876e11, 0.0]
dirichlet_values_o = [3.0680511120e13, 0.0]

[output]
ncycle_out = 250
#dt_hdf5 = 1.0e-15 # default: 100 outputs
dt_init_frac = 1.001

[output.history]
fn = "rad_shock.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 2
porder = 2

[fluid.limiter]
do_limiter = true
type = "minmod"
m_tvb = 4.0
b_tvd = 1.0
tci_opt = true
tci_val = 2.0
characteristic = false

[radiation]
basis = "legendre"
nnodes = 2
porder = 2

[radiation.limiter]
type = "minmod"
m_tvb = 0.0
b_tvd = 1.0
tci_opt = false
tci_val = 0.1
characteristic = false

[time]
#integrator = "IMEX_SSPRK11"
#integrator = "IMEX_SSPRK22_DIRK" # bad
#integrator = "IMEX_ARK32_ESDIRK"
integrator = "IMEX_PDARS_ESDIRK"

[eos]
type = "ideal"
gamma = 1.66666666666667 # default: 1.4

[opacity]
type = "constant"
kP = 577.0 # cm^2 / g
kR = 577.0 # cm^2 / g
