[problem]
problem = "rad_equilibrium"
t_end = 1.0e-7
geometry = "planar"
restart = false
do_rad = true
xl = 0.0
xr = 1.0
bc = "homogenous"
cfl = 0.5

[problem.params]
v0 = 0.0
logrho = -7.0
logE_gas = 10.0
logE_rad = 12.0

[output]
nlim = -1
ncycle_out = 100
#dt_hdf5 = 1.0e-10 # default: 100 outputs
dt_init_frac = 1.05

[fluid]
basis = "legendre"
nnodes = 1
porder = 1
nx = 16
ng = 1

[time]
torder = 2
nstages = 2

[limiters]
tci_opt = false
tci_val = 0.1
characteristic = false
