[problem]
problem = "rad_advection"
t_end = 1.0e-10
geometry = "planar"
restart = false
do_rad = true
xl = 0.0
xr = 1.0
cfl = 0.85

[problem.params]
v0 = 0.0
rho = 1.0
amp = 1.0
width = 0.05

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"
[bc.rad]
bc_i = "outflow"
bc_o = "outflow"

[output]
nlim = -1
ncycle_out = 100
dt_init_frac = 1.001
#dt_hdf5 = 1.0e-2 # default: 100 outputs

[fluid]
basis = "legendre"
nnodes = 1
porder = 1
nx = 128
ng = 1

[time]
integrator = "IMEX_SSPRK22_DIRK"
torder = 2
nstages = 2

[eos]
type = "ideal"
ideal_gamma = 1.66666666666667 # default: 1.4

[limiters]
tci_opt = false
tci_val = 0.1
characteristic = false
