[problem]
problem = "rad_shock"
t_end = 1.0e-9
geometry = "planar"
restart = false
do_rad = true
xl = 0.0
xr = 0.01575
x_d = 0.013
bc = "homogenous"
cfl = 0.05

# Mach 3 Case:
# - Left side (pre-shock):
#   - Density: 5.69 g/cm^3
#   - Velocity: 5.19e7 cm / s
#   - Temperature: 2.18e6 K
# - Right side (post-shock):
#   - Density: 17.1 g/cm^3
#   - Velocity: 1.73e7 cm/s
#   - Temperature: 7.98e6 K
[problem.params]
vL = 5.19e7
vR = 1.73e7
rhoL = 5.69
rhoR = 17.1 
T_L = 2.18e6
T_R = 7.98e6

[output]
nlim = -1
ncycle_out = 200
dt_hdf5 = 1.0e-12 # default: 100 outputs
dt_init_frac = 1.1

[fluid]
basis = "legendre"
nnodes = 2
porder = 2
nx = 64
ng = 1

[time]
torder = 2
nstages = 2

[eos]
type = "ideal"
ideal_gamma = 1.66666666666667 # default: 1.4

[opacity]
type = "constant"
kP = 577.0 # cm^2 / g
kR = 577.0 # cm^2 / g

[limiters]
type = "minmod"
tci_opt = false
tci_val = 0.1
characteristic = false
