[problem]
problem = "rad_equilibrium"
t_end = 1.0e-7
nlim = -1
geometry = "planar"
restart = false
xl = 0.0
xr = 1.0
cfl = 0.8
nx = 2
grid_type = "uniform"

[problem.params]
v0 = 0.0
logrho = -7.0
logE_gas = 10.0
logE_rad = 12.0

[physics]
radiation = true
gravity = false
composition = false
ionization = false
heating = false

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"
[bc.radiation]
bc_i = "outflow"
bc_o = "outflow"

[output]
ncycle_out = 100
#dt_hdf5 = 1.0e-12 # default: 100 outputs
dt_init_frac = 1.005

[output.history]
fn = "rad_equilibrium.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 1
porder = 1

[fluid.limiter]
tci_opt = false
tci_val = 0.1
characteristic = false

[radiation]
basis = "legendre"
nnodes = 1
porder = 1

[radiation.limiter]
tci_opt = false
tci_val = 0.1
characteristic = false

[time]
integrator = "IMEX_SSPRK11"
#integrator = "IMEX_PDARS_ESDIRK"

[eos]
type = "ideal"
gamma = 1.66666666666667 # default: 1.4

[opacity]
type = "powerlaw_rho"
kP = 4.0e-8 # 1 / cm
kR = 4.0e-8 # 1 / cm
exp = -1.0
