[problem]
problem = "rad_advection"
t_end = 1.0e-10
nlim = -1
geometry = "planar"
restart = false
xl = 0.0
xr = 1.0
cfl = 0.85
nx = 128

[problem.params]
v0 = 0.0
rho = 1.0
amp = 1.0
width = 0.05

[physics]
radiation = true
gravity = false

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"
[bc.radiation]
bc_i = "outflow"
bc_o = "outflow"

[output]
ncycle_out = 100
dt_init_frac = 1.001
#dt_hdf5 = 1.0e-2 # default: 100 outputs

[output.history]
fn = "rad_advection.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 1
porder = 1

[fluid.limiter]
tci_opt = false
tci_val = 0.1
characteristic = false

[radiation]
basis = "legendre"
nnodes = 1
porder = 1

[radiation.limiter]
tci_opt = false
tci_val = 0.1
characteristic = false

[time]
integrator = "IMEX_SSPRK22_DIRK"

[eos]
type = "ideal"
gamma = 1.66666666666667 # default: 1.4

[opacity]
type = "powerlaw_rho"
kP = 4.0e-8 # 1 / cm
kR = 4.0e-8 # 1 / cm
exp = -1.0
