[Problem]
problem=RadEquilibrium
t_end=1.0e-7
geometry=planar;spherical or planar
restart=false
do_rad=true
xL=0.0
xR=1.0
BC=Homogenous
CFL=0.35

[Fluid]
Basis=Legendre
nNodes=1
pOrder=1
nX=256
nG=1

[Time]
tOrder=1
nStages=1

[Limiters]
alpha=1.0
Threshold=0.0
TCI_Opt=false
TCI_val=0.1
Characteristic=true
