[problem]
problem = "sedov"
t_end = 0.5
geometry = "planar"
restart = false
do_rad = false
xl = -1.0
xr = 1.0
bc = "homogenous"
cfl = 0.35

[problem.params]
v0 = 0.0
rho0 = 1.0
E0 = 0.3

[fluid]
basis = "legendre"
nnodes = 2
porder = 2
nx = 512
ng = 1

[time]
torder = 3
nstages = 5

[limiters]
tci_opt = false
tci_val = 0.1
characteristic = true
gamma_i = 0.8
#gamma_r = 0.005
#gamma_l = 0.005
