[problem]
problem = "sedov"
t_end = 0.05
geometry = "spherical"
restart = false
do_rad = false
do_gravity = false
xl = 0.0
xr = 1.0
cfl = 0.25

[problem.params]
v0 = 0.0
rho0 = 1.0
E0 = 0.5

[bc]
[bc.fluid]
bc_i = "reflecting"
bc_o = "outflow"

[output]
nlim = -1
ncycle_out = 100
dt_hdf5 = 0.001
dt_init_frac = 1.05

[output.history]
fn = "sedov.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 3
porder = 3
nx = 256
ng = 1

[gravity]
model = "constant"
gval = 1.0

[time]
integrator = "EX_SSPRK54"

[eos]
type = "ideal"
gamma_ideal = 1.4

[limiters]
do_limiter = true
type = "minmod"
b_tvd = 0.0
m_tvb = 0.0
tci_opt = true
tci_val = 0.25
characteristic = false
gamma_i = 0.9
#gamma_r = 0.005
#gamma_l = 0.005
weno_r = 2.0
