[problem]
problem = "shockless_noh"
t_end = 0.5
geometry = "planar"
restart = false
xl = 0.0
xr = 1.0
cfl = 0.35
nx = 128

[problem.params]
rho = 1.0
specific_energy = 1.0

[physics]
radiation = false
gravity = false

[bc]
[bc.fluid]
bc_i = "reflecting"
bc_o = "reflecting"

[output]
nlim = -1
ncycle_out = 100
dt_hdf5 = 0.05

[output.history]
fn = "shockless_noh.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 2
porder = 2

[fluid.limiter]
tci_opt = false
tci_val = 0.1
characteristic = true
gamma_i = 0.8

[time]
integrator = "EX_SSPRK22"

[eos]
type = "ideal"
gamma = 1.4
