[problem]
problem = "shu_osher"
t_end = 1.8
geometry = "planar"
restart = false
do_rad = false
xl = -5.0
xr = 5.0
cfl = 0.35

[problem.params]
v0 = 2.629369
rhoL = 3.857143
pL = 10.33333333
pR = 1.0

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"

[output]
nlim = -1
ncycle_out = 100
dt_hdf5 = 1.0e-2

[fluid]
basis = "legendre"
nnodes = 1
porder = 1
nx = 256
ng = 1

[time]
integrator = "EX_SSPRK33"

[eos]
type = "ideal"
gamma_ideal = 1.4

[limiters]
do_limiter = true
type = "minmod"
weno_r = 2.0
tci_opt = false
tci_val = 0.1
characteristic = false
gamma_i = 0.8
#gamma_r = 0.005
#gamma_l = 0.005
