[problem]
problem = "shu_osher"
t_end = 1.8
nlim = -1
geometry = "planar"
restart = false
xl = -10.0
xr = 10.0
cfl = 0.35
nx = 128
grid_type = "uniform"

[problem.params]
v0 = 2.629369
rhoL = 3.857143
pL = 10.33333333
pR = 1.0

[physics]
radiation = false
gravity = false
composition = false
ionization = false

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"

[output]
ncycle_out = 100
dt_hdf5 = 1.0e-2

[output.history]
fn = "shu_osher.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
<<<<<<< Updated upstream
nnodes = 2
porder = 2

[fluid.limiter]
do_limiter = true
type = "minmod"
b_tvd = 1.0
m_tvb = 0.0
tci_opt = false
tci_val = 0.1
characteristic = false

[time]
integrator = "EX_SSPRK33"

[eos]
type = "ideal"
gamma = 1.4
