[problem]
problem = "shu_osher"
t_end = 0.1
geometry = "planar"
restart = false
do_rad = false
xl = 0.0
xr = 1.0
bc = "homogenous"
cfl = 0.35

[problem.params]
v0 = 2.629369
rhoL = 3.857143
pL = 10.33333333
pR = 1.0

[output]
nlim = -1
ncycle_out = 100
dt_hdf5 = 1.0e-2

[fluid]
basis = "legendre"
nnodes = 2
porder = 2
nx = 512
ng = 1

[time]
torder = 2
nstages = 2

[eos]
type = "ideal"

[limiters]
tci_opt = true
tci_val = 0.1
characteristic = true
gamma_i = 0.998
#gamma_r = 0.005
#gamma_l = 0.005
