[problem]
problem = "smooth_flow"
t_end = 0.5
geometry = "planar"
restart = false
xl = 0.0
xr = 1.0
cfl = 0.5
nx = 128

[problem.params]
amp = 0.99999999999999

[physics]
radiation = false
gravity = false

[bc]
[bc.fluid]
bc_i = "periodic"
bc_o = "periodic"

[output]
nlim = -1
ncycle_out = 100
dt_hdf5 = 0.1

[output.history]
fn = "smooth_flow.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 1
porder = 1

[fluid.limiter]
tci_opt = false
tci_val = 0.1
characteristic = true
gamma_i = 0.8

[time]
integrator = "EX_SSPRK22"

[eos]
type = "ideal"

