[problem]
problem = "smooth_flow"
t_end = 0.5
geometry = "planar"
restart = false
do_rad = false
xl = 0.0
xr = 1.0
bc = "periodic"
cfl = 0.5

[problem.params]
amp = 0.99999999999999

[output]
nlim = -1
ncycle_out = 100
dt_hdf5 = 0.1

[fluid]
basis = "legendre"
nnodes = 2
porder = 2
nx = 128
ng = 1

[time]
torder = 2
nstages = 2

[limiters]
tci_opt = false
tci_val = 0.1
characteristic = true
gamma_i = 0.8
