[problem]
problem = "smooth_flow"
t_end = 0.5
geometry = "planar"
restart = false
do_rad = false
xl = 0.0
xr = 1.0
cfl = 0.5

[problem.params]
amp = 0.99999999999999

[bc]
[bc.fluid]
bc_i = "periodic"
bc_o = "periodic"

[output]
nlim = -1
ncycle_out = 100
dt_hdf5 = 0.1

[fluid]
basis = "legendre"
nnodes = 1
porder = 1
nx = 128
ng = 1

[time]
integrator = "EX_SSPRK22"
torder = 2
nstages = 2

[eos]
type = "ideal"

[limiters]
tci_opt = false
tci_val = 0.1
characteristic = true
gamma_i = 0.8
