[Problem]
problem = "Sod"
t_end = 0.2
geometry = "planar"
restart = false
do_rad = false
xL = 0.0
xR = 1.0
BC = "Homogenous"
CFL = 0.35

[Fluid]
Basis = "legendre"
nNodes = 3
pOrder = 3
nX = 512
nG = 1

[Time]
tOrder = 3
nStages = 5

[Limiters]
TCI_Opt = false
TCI_val = 0.1
Characteristic = true
gamma_i = 0.990
gamma_r = 0.005
gamma_l = 0.005
