[problem]
problem = "sod"
t_end = 0.1
geometry = "planar"
restart = false
do_rad = false
xl = 0.0
xr = 1.0
bc = "homogenous"
cfl = 0.35

[problem.params]
v0 = 0.0
rhoL = 1.0
rhoR = 0.125
pL = 1.0
pR = 0.1

[output]
nlim = -1
ncycle_out = 100
dt_hdf5 = 1.0e-2
dt_init_frac = 5.0

[fluid]
basis = "legendre"
nnodes = 1
porder = 1
nx = 512
ng = 1

[time]
torder = 1
nstages = 1

[eos]
type = "ideal"
ideal_gamma = 1.4 # default: 1.4

[limiters]
tci_opt = false
tci_val = 0.1
characteristic = true
gamma_i = 0.998
#gamma_r = 0.005
#gamma_l = 0.005
