[problem]
problem = "sod"
t_end = 0.2
geometry = "planar"
restart = false
do_rad = false
xl = 0.0
xr = 1.0
cfl = 0.8

[problem.params]
vL = 0.0
vR = 0.0
rhoL = 1.0
rhoR = 0.125
pL = 1.0
pR = 0.1
x_d = 0.5

#[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"

[output]
nlim = -1
ncycle_out = 100
#dt_hdf5 = 2.5e-2
dt_init_frac = 1.1

[fluid]
basis = "legendre"
nnodes = 3
porder = 3
nx = 256
ng = 1

[time]
integrator = "EX_SSPRK33"

[eos]
type = "ideal"
ideal_gamma = 1.4 # default: 1.4

[limiters]
do_limiter = true
type = "minmod"
m_tvb = 100.0
b_tvd = 1.0
tci_opt = true
tci_val = 0.05
#tci_val = 0.6
characteristic = false
gamma_i = 0.5
weno_r = 2.0
