[Problem]
problem = "Sod"
t_end = 0.1
geometry = "planar"
restart = false
do_rad = false
xL = 0.0
xR = 1.0
BC = "Homogenous"
CFL = 0.35

[Fluid]
Basis = "legendre"
nNodes = 1
pOrder = 1
nX = 512
nG = 1

[Time]
tOrder = 1
nStages = 1

[Limiters]
TCI_Opt = false
TCI_val = 0.1
Characteristic = true
gamma_i = 0.998
#gamma_r = 0.005
#gamma_l = 0.005
