[problem]
problem = "sod"
t_end = 0.2
nlim = -1
geometry = "planar"
restart = false
xl = 0.0
xr = 1.0
cfl = 0.5
nx = 256

[physics]
radiation = false
gravity = false
composition = false
ionization = false

[problem.params]
vL = 0.0
vR = 0.0
rhoL = 1.0
rhoR = 0.125
pL = 1.0
pR = 0.1
x_d = 0.5

#[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"

[output]
ncycle_out = 100
#dt_hdf5 = 2.5e-2
dt_init_frac = 1.1

[output.history]
fn = "sod.hst"
dt = 0.001

[fluid]
basis = "legendre"
nnodes = 3
porder = 3

[fluid.limiter]
do_limiter = true
type = "minmod"
m_tvb = 10.0
b_tvd = 1.0
tci_opt = true
tci_val = 0.075
characteristic = false

[time]
integrator = "EX_SSPRK33"

[eos]
type = "ideal"
gamma = 1.4 # default: 1.4
