[problem]
problem = "sod"
t_end = 0.4
nlim = -1
geometry = "planar"
restart = false
xl = 0.0
xr = 5.0
cfl = 0.8
nx = 256
grid_type = "uniform"

[physics]
radiation = false
gravity = false
composition = false
ionization = false

[problem.params]
vL = 0.0
vR = 0.0
rhoL = 10.0
rhoR = 1.0
pL = 100.0
pR = 1.0
x_d = 2.0

[bc]
[bc.fluid]
bc_i = "outflow"
bc_o = "outflow"

[output]
ncycle_out = 100
dt_hdf5 = 1.0e-2
dt_init_frac = 1.5

[output.history]
fn = "sod.hst"
#dt = 0.001 # default: dt_hdf5 / 10

[fluid]
basis = "legendre"
nnodes = 3
porder = 3

[fluid.limiter]
do_limiter = true
type = "minmod"
m_tvb = 0.0
b_tvd = 1.0
tci_opt = true
tci_val = 0.12
characteristic = true
gamma_i = 0.1
#gamma_r = 0.005
#gamma_l = 0.005
#b_tvd = 2.0 #minmod
#m_tvb = 1.0 #minmod

[time]
integrator = "EX_SSPRK54"

[eos]
type = "ideal"
gamma = 1.4 # default: 1.4
