name: Check Formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    formatting:
      name: Check C++ Formatting
      runs-on: ubuntu-latest

      steps:      
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set system to non-interactive mode
          run: export DEBIAN_FRONTEND=noninteractive
        - name: Install the latest version of uv
          uses: astral-sh/setup-uv@v3
          with:
            version: "latest"
        - name: install dependencies
          run: |
            uv pip install "clang-format==19.1.0"
        - name: check formatting
          run: find . -regex '.*\.\(cpp\|hpp\)' | xargs clang-format -style=file -i && git diff --exit-code --ignore-submodules
