name: Check Formatting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    formatting:
      name: Check Formatting
      runs-on: ubuntu-latest

      steps:      
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set system to non-interactive mode
          run: export DEBIAN_FRONTEND=noninteractive
        - name: Get Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
        - name: install dependencies
          run: |
            python -m pip install --upgrade pip
            python -m pip install clang-format
            #sudo apt-get install -y --force-yes -qq git clang
        - name: check formatting
          run: find . -regex '.*\.\(cpp\|hpp\)' | xargs clang-format -style=file -i && git diff --exit-code --ignore-submodules
